### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.github.demidko.aot.WordformMeaning

### ISSUE THREAD

**Issue by lashnag** [demidko/aot#8]
Привет! А ты не сталкивался с ошибкой java.lang.NoClassDefFoundError: Could not initialize class com.github.demidko.aot.WordformMeaning?
Я разворачиваю в докер контейнере и на локалке работает, а на хосте нет. Прям замучался искать - может подскажешь? https://github.com/lashnag/forwarder-backend/blob/main/src/main/kotlin/ru/lashnev/forwarderbackend/services/MessageCheckerService.kt#L12

**Comment by demidko** [comment]
@lashnag Я не думаю что это проблема библиотеки) Потому что на хосте у тебя может быть что угодно, так много вопросов, и так мало ответов. Но попробовать помочь можно. Что за хост машина? Какая версия java на ней? Как именно собираешь? Если ты используешь maven для сборки, тебе нужно делать fat-jar, делаешь? Как именно запускаешь?

При возникновении этой ошибки, для начала тебе нужно распаковать fat-jar и убедиться что этот класс физически присутствует, попал в билд.

**Comment by demidko** [comment]
@lashnag Попробуй явно сконфигурировать `spring-boot-maven-plugin` в файле `pom.xml`

```xml
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <executable>true</executable>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

После этого выполняешь `mvn clean package` и запускаешь перепакованную jar-ку из target, а не стандартную-худую.

**Comment by demidko** [comment]
@lashnag  Помогло?

**Comment by demidko** [comment]
Кстати, на строке 13 ниже ты берешь лемму 1ой словоформы. Но это может быть ошибкой. Ты должен брать леммы всех словоформ. Потому что ты не знаешь какая именно оригинальная словоформа

**Comment by lashnag** [comment]
> Кстати, на строке 13 ниже ты берешь лемму 1ой словоформы. Но это может быть ошибкой. Ты должен брать леммы всех словоформ. Потому что ты не знаешь какая именно оригинальная словоформа

Я привожу и слово, которое ищу и все слова в предложении. Поэтому должно сработать

**Comment by demidko** [comment]
@lashnag я про то, что лемм может быть больше, и из-за того что ты всегда берешь только первую, поиск будет что нибудь упускать. У одного и того же слова может быть несколько лемм. Надо бы делать `it else wordParts.map{ it.lemma }`, а затем ниже в пайпе `flatten()`

**Comment by demidko** [comment]
@lashnag например если в тексте будет слово замок, у него может быть лемма как замок (в смысле строения) так и замокнуть (в смысле под дождем). И ниже ты проделываешь такую же неполную лемматизацию с ключевыми словами, выбирая 0ую лемму, хотя нет никаких гарантий что она чем-то лучше остальных.

**Comment by demidko** [comment]
@lashnag а для тех слов где ничего не нашел в морфологии нужно дополнительно делать стемминг, для этого много библиотек

**Comment by lashnag** [comment]
> @lashnag Я не думаю что это проблема библиотеки) Потому что на хосте у тебя может быть что угодно, так много вопросов, и так мало ответов. Но попробовать помочь можно. Что за хост машина? Какая версия java на ней? Как именно собираешь? Если ты используешь maven для сборки, тебе нужно делать fat-jar, делаешь? Как именно запускаешь?
> 
> При возникновении этой ошибки, для начала тебе нужно распаковать fat-jar и убедиться что этот класс физически присутствует, попал в билд.

А имеет значение харакетиристики джавы на хост машине?  У меня java из окружения контейнера для сборки https://github.com/lashnag/forwarder-backend/blob/main/Dockerfile

**Comment by lashnag** [comment]
> @lashnag Попробуй явно сконфигурировать `spring-boot-maven-plugin` в файле `pom.xml`
> 
> ```
>       <plugin>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-maven-plugin</artifactId>
>         <configuration>
>           <executable>true</executable>
>         </configuration>
>         <executions>
>           <execution>
>             <goals>
>               <goal>repackage</goal>
>             </goals>
>           </execution>
>         </executions>
>       </plugin>
> ```
> 
> После этого выполняешь `mvn clean package` и запускаешь перепакованную jar-ку из target, а не стандартную-худую.

К сож не помогло

Вот что в не упакованном проекте

~/IdeaProjects/forwarder-backend git:[main]
mvn dependency:tree | grep demidko
[INFO] +- com.github.demidko:aot:jar:2022.11.28:compile
[INFO] |  +- com.github.demidko:bits:jar:2022.08.06:compile
[INFO] |  \- com.github.demidko:aot-bytecode:jar:2021.10.29:compile

Вот что в упакованном jar
BOOT-INF/lib -> aot-2022.11.28.jar, aot-bytecode-2021.10.29.jar

Класс явно есть - но как буд-то не загружается

# unzip aot-2022.11.28.jar -d aop
Archive:  aot-2022.11.28.jar
   creating: aop/META-INF/
  inflating: aop/META-INF/MANIFEST.MF  
   creating: aop/com/
   creating: aop/com/github/
   creating: aop/com/github/demidko/
   creating: aop/com/github/demidko/aot/
  inflating: aop/com/github/demidko/aot/WordformMeaning.class  
  inflating: aop/com/github/demidko/aot/AotReader.class  
  inflating: aop/com/github/demidko/aot/PartOfSpeech$1.class  
  inflating: aop/com/github/demidko/aot/PartOfSpeech.class  
  inflating: aop/com/github/demidko/aot/ByteBlock.class  
  inflating: aop/mrd.gz

**Comment by demidko** [comment]
@lashnag то есть, я правильно понимаю, что собранный jar запускается на локальной машине, но падает с этой ошибкой на проде, на хост машине?

**Comment by demidko** [comment]
@lashnag у тебя в примере откуда-то взялся пакет `aop`, тогда как он в коде называется `aot`. Полагаю дело в этом

**Comment by demidko** [comment]
@lashnag аа, то есть один и тот же докер контейнер запускается локально, но не запускается на хост-машине? Тогда интересно что это за хост машина такая

**Comment by demidko** [comment]
@lashnag тебе надо не aot-jar'ку проверять, а свою собственную которую собрал, что в ней лежит? То есть, залазишь в запущенный контейнер и там jar'ку потрошишь

**Comment by demidko** [comment]
Закрыт т.к. проблема не на стороне библиотеки
